spring:
  application:
    name: qiyu-live-user-provider
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:qiyu-db-sharding.yaml
    hikari:
      pool-name: qiyu-user-pool
      minimum-idle: 150
      maximum-pool-size: 300
      connection-timeout: 4000
      max-lifetime: 60000
  data:
    redis:
      port: 6379
      #      host: 127.0.0.1
      host: 192.168.56.129
      lettuce:
        pool:
          min-idle: 10
          max-idle: 20
          max-active: 50
      password: 123456
qiyu:
  rmq:
    producer:
      nameServer: 127.0.0.1:9876
      groupName: ${spring.application.name}
      retryTimes: 3
      sendTimeOut: 3000
    consumer:
      nameServer: 127.0.0.1:9876
      groupName: ${spring.application.name}

dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  registry:
    address: nacos://127.0.0.1:8848?namespace=qiyu-live-test&&username=qiyu&&password=qiyu
  protocol:
    name: dubbo
    port: 9090
